- package-lock.json
- reservant-frontend/package-lock.json
- reservant-frontend/package.json
- reservant-frontend/src/app/App.tsx
- reservant-frontend/src/components/login/InputField.tsx
- reservant-frontend/src/components/login/Login.tsx
Created a new Login component and a reusable InputField component
> Added Login component

- package-lock.json
- src/translations/en/global.json
- src/translations/pl/global.json
dodane polskie tłumaczenie istniejących już fragmentów
> feat: polski język

- src/components/navigation/Navigation.tsx
- src/components/restaurant/management/Group.tsx
- src/components/restaurant/management/GroupsList.tsx
- src/components/restaurant/management/MyGroups.tsx
- src/components/restaurant/management/RestaurantDetails.tsx
- src/components/restaurant/management/RestaurantManager.tsx
- Restaurant management screen
- Component for rendering owner's restaurant groups
> Restaurant management screen

- src/components/restaurant/management/Group.tsx
- src/components/restaurant/management/MyGroups.tsx
- src/components/restaurant/management/RestaurantData.tsx
- src/components/restaurant/management/RestaurantDetails.tsx
- src/components/restaurant/management/RestaurantManager.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
- need to fix headers in fetch requests later
- add translations to restaurant data
- fixed translation issues in MyGroups
- added some layout for showcasing restaurant's data (RestaurantData.tsx)
- MyGroups and Group is less ugly now
> Initial plan for the restaurant data component

- src/components/register/EmployeeRegister.tsx
- src/components/register/UserRegister.tsx
- src/hooks/useValidationSchema.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
made "login taken" validation to run not only on submit and added its error to errorMessage component.
please refer to the onChange and onBlur validation issue
> fix: errors

- src/components/Loader.tsx
- src/components/management/RestaurantManagement/Group.tsx
- src/components/management/RestaurantManagement/MyGroups.tsx
added loader component and used it when groups or restaurants are empty
> feat: loader component

- src/components/Login.tsx
- src/components/management/MenuManagement/MenuItem.tsx
- src/components/management/MenuManagement/MenuMangement.tsx
- src/components/management/MenuManagement/MenuPopup.tsx
- src/components/management/RestaurantManagement/ManagementSection.tsx
- src/components/management/RestaurantManagement/RestaurantAddEmp.tsx
- src/components/management/RestaurantManagement/RestaurantDetails.tsx
- src/components/management/RestaurantManagement/restaurantReviews/RestaurantReview.tsx
- src/components/management/RestaurantManagement/restaurantReviews/RestaurantReviewsFilters.tsx
- src/components/navigation/navItems/AuthItems.tsx
- src/components/navigation/navItems/LanguageChange.tsx
- src/components/navigation/navItems/MenuSection.tsx
- src/components/navigation/navItems/ThemeButton.tsx
- src/components/navigation/navItems/Tools.tsx
- src/components/register/EmployeeRegister.tsx
- src/components/register/RestaurantRegister.tsx
- src/components/register/UserRegister.tsx
- src/components/register/restaurantRegister/RestaurantRegister.tsx
- src/components/reusableComponents/Popup.tsx
added all buttons i could find ids
> feat: buttons ID

- src/components/management/EmployeeManagement/EmployeeManagement.tsx
- src/components/management/RestaurantManagement/RestaurantDetails.tsx
- src/components/navigation/NavBar.tsx
- src/components/navigation/navItems/MenuSections.tsx
- src/index.tsx
added grid buttons ids based on emp login
fixed sections ids
> feat: buttonIDs

- package-lock.json
- src/components/HomePage.tsx
- src/components/navigation/NavBar.tsx
- src/components/navigation/navItems/FriendRequest.tsx
- src/components/navigation/navItems/FriendSearchBar.tsx
- src/components/navigation/navItems/NotificationsButton.tsx
- src/components/restaurant/view/FocusedRestaurantDetails.tsx
- src/components/restaurant/view/FocusedRestaurantMenuItem.tsx
- src/components/restaurant/view/FocusedRestaurantMenuList.tsx
- src/components/restaurant/view/FocusedRestaurantReviewsList.tsx
- added friend search bar
- added notifications button with friend requests
- added a view for restaurant details when on map view
> a few features

- src/components/map/Map.tsx
- src/components/restaurant/view/FocusedRestaurantDetails.tsx
- src/components/restaurant/view/FocusedRestaurantMenuList.tsx
- src/components/restaurant/view/FocusedRestaurantReviewsList.tsx
- src/components/restaurant/view/MenuItemComponent.tsx
- src/components/restaurant/view/RestaurantCart.tsx
- src/components/restaurant/view/RestaurantDetails.tsx
- src/components/restaurant/view/RestaurantMenuView.tsx
- src/components/restaurant/view/RestaurantView.tsx
- src/components/routing/Routing.tsx
- Fixed (i think) opinions and menu items sticking out of DetailedReestaurant
- RestaurantDetails:
1. Getting restaurant and menu data from backend
2. components are now (somewhat) responsive to browser window changes
3. Working map that shows restaurant coordinates
4. Changed the layout of the component a bit
> A few changes in RestaurantDetails and FocusedRestaurantDetails

- src/components/restaurantManagement/RestaurantManager.tsx
- src/components/restaurantManagement/reservations/OrderHistory.tsx
- src/components/restaurantManagement/reservations/ReservationHistoory.tsx
- src/components/restaurantManagement/reservations/ReservationOrderHeader.tsx
Zmieniłam wygląd tabeli dla order History ze zwykłej na collapsable
> Reservation history

- src/components/navigation/navItems/FriendSearchBar.tsx
- src/components/navigation/navItems/NotificationList.tsx
- src/components/navigation/navItems/NotificationsButton.tsx
- src/components/navigation/navItems/SendFriendRequest.tsx
- src/components/routing/Routing.tsx
- src/services/APIconn.tsx
Implemented sending and accepting friend requests
- deleting friends and friend request doesn't work for now on the backend, so couldn't implement that
- for now no endpoint to fetch other users so i just had to list them by hand
> Implemented sending and accepting friend requests

- src/components/restaurantManagement/employees/EmploymentsManagement.tsx
- src/services/APIconn.tsx
> Feat jg employments update

- src/components/HomePage.tsx
- src/components/restaurant/view/OnMapView/FocusedRestaurantDetails.tsx
- src/components/restaurant/view/RestaurantPageView/RestaurantCreateEvent.tsx
- src/components/restaurant/view/RestaurantPageView/RestaurantDetails.tsx
- src/components/restaurant/view/RestaurantPageView/RestaurantEventsView.tsx
- src/components/restaurant/view/RestaurantPageView/RestaurantView.tsx
- src/components/routing/Routing.tsx
- Added new endpoint in Routing.tsx for restaurant view
- Button in map restaurant view correctly redirects to restaurant page view
- Changed hardcoded restaurant id to real ones (for restaurant map view and restaurant full page view), replaced all hardcoded values with real ones
- Started events: 
- 1) correctly fetching from backend
- 2) can create new events, but with hardcoded dates, for now
> Started events, fixed hardcoded restaurants

- src/components/restaurant/view/MenuItemComponent.tsx
- src/components/restaurant/view/OnMapView/FocusedRestaurantMenuList.tsx
- src/components/restaurant/view/RestaurantPageView/RestaurantCartView.tsx
- src/components/restaurant/view/RestaurantPageView/RestaurantDetails.tsx
- src/components/restaurant/view/RestaurantPageView/RestaurantMenuView.tsx
- src/components/restaurant/view/RestaurantPageView/RestaurantView.tsx
- src/components/restaurantManagement/menus/MenuItem.tsx
- src/services/interfaces.tsx
#108 - In Restaurant preview on the map  (FocusedRestaurantMenuList.tsx) Now by default the first menu is always active 
#109 - Different items are now correctly added to the cart (RestaurantView.tsx) 
#110 - A different component renders if a restaurant doesn't have any photos in their gallery (RestaurantDetails.tsx). Additionally added some borders for different sections of the restaurant for a better look 
#112 - Menus for different restaurants now render correctly when user changes the active restaurant (FocusedRestaurantMenuList.tsx)
> Fixed assigned Github issues

- Dockerfile
- Jenkinsfile
Bez tego nie działały requesty
> Naprawiono ustawienie zmiennych środowiskowych

- package-lock.json
- package.json
- src/components/SignInSignUp/UserRegister.tsx
- src/hooks/useValidationSchema.tsx
css: fixed transitions
css: fixed phone number field
yup: fixed phone number validation
#122
> user register tweaks

- src/components/restaurant/events/CreateEventThread.tsx
- src/components/restaurant/events/EventCreationModal.tsx
- src/components/restaurant/events/EventDetailsModal.tsx
- src/components/restaurant/events/EventEditModal.tsx
- src/components/restaurant/events/MyEventsModal.tsx
- src/components/restaurant/events/RemoveEventConfirmation.tsx
- src/components/restaurant/events/RemoveEventInterest.tsx
- src/components/restaurant/events/RestaurantEventDetails.tsx
- src/components/restaurant/events/RestaurantEventsModal.tsx
- src/components/restaurant/view/OnMapView/FocusedRestaurantDetails.tsx
- src/components/restaurant/view/OnMapView/FocusedRestaurantReviewsList.tsx
- Podpięcie eventów
- Kilka zmian w stylach dark/light mode żeby działały
- Dodanie nowego atrybutu
- Wyłączenie opcji edycji eventów które już się odbyły
- +fix: Wyśrodkowanie tekstu w przycisku make a reservation
> Events continuation

- src/app/App.tsx
- src/components/profile/EventHistory.tsx
- src/components/profile/FriendsManagement.tsx
- src/components/profile/Profile.tsx
Friends Tab on profile allowing to remove an existing friend and manage outgoing friend requests
> Friends Management tab on Profile (in progress)

- src/components/profile/Account.tsx
- src/components/profile/EventDetails.tsx
- src/components/profile/EventHistory.tsx
- src/components/profile/ProfileTabs.tsx
- src/components/restaurant/onMapView/FocusedRestaurantEventDetails.tsx
- src/components/restaurant/onMapView/FocusedRestaurantEventsList.tsx
- Rozdzielenie EventHistory na 3 komponenty: ProfileTabs (zakładki), EventHistory (lista eventów), EventDetails (szczegóły konkretnego eventu)
- w Działo się wyświetla się tylko EventHistory i EventDetails
- Naprawienie w Profilu Wyświetlanie Eventów InterestedIn i ParticipateIn
- Dodano zarządzanie członkami eventu (Eventów utworzonych przez zalogowanego użytkownika)
- Naprawiono w FocusedRestaurantView dla Eventu przycisk do Wyrażenia zainteresowania (Teraz jeżeli jest się już zainteresowanym to wyśle fetchDELETE zamiast kolejnego fetchPOST)
> a few changes to events

- src/components/profile/FriendsManagement.tsx
- src/components/profile/Profile.tsx
- Zakładka przychodzących zaproszeń do znajomych, z której można wyświetlić wszystkie przychodzące zaproszenia i potwierdzić lub anulować zaproszenie
> Incoming requests tab in Profile's Friends tab

- src/components/profile/events/Event.tsx
- src/components/profile/events/EventDialog.tsx
- src/components/profile/events/EventList.tsx
- src/services/types.ts
- Functions for events working again
- Changed multiple dialogs to one, and moved it to a separate component named EventDialog
> Event's functions restored

- src/components/reservant/navigation/navItems/Tools.tsx
navbar dropdown menu button ids
> navbar dropdown menu button ids

- src/components/reservant/restaurant/events/EventCreationModal.tsx
- src/components/reservant/restaurantManagement/Warehouse/AddIngredientDialog.tsx
- src/components/reservant/restaurantManagement/Warehouse/EditIngredientDialog.tsx
- src/components/reservant/restaurantManagement/Warehouse/GroceryInfoDialog.tsx
- src/components/reservant/restaurantManagement/Warehouse/GroceryListDialog.tsx
- src/components/reservant/restaurantManagement/Warehouse/IngredientTable.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
- Fix: Przyciski tworzenia eventu w formularzu się wyświetlają przy różnych przybliżeniach strony
- Fix: Grocery list wyświetla się w dialogu na środku ekranu, jeżeli nie ma żadnych składników 'Out of stock' to wyświetla o tym komunikat zamiast pustej tabeli
- Feature: Do Grocery list można dodawać składniki, które nie są out of stock, ale też chcemy je zamówić
- Feature: Edycja (POST i PUT) składników zaimplementowana
- Feature: Uaktualnienie komponentu IngredientsTable (wyczyszczenie, rozdzielenie na więcej komponentów, zamiana MUI Dialog na te z reusableComponents)
> IngredientsTable and Events form fixes

- src/components/reservant/restaurant/events/EventCreationModal.tsx
> Issue #221

- src/components/reservant/feed/Feed.tsx
- src/components/reservant/profile/Account.tsx
- src/components/reservant/profile/Profile.tsx
- src/components/reservant/profile/events/Event.tsx
- src/components/reservant/profile/events/EventList.tsx
- src/components/reservant/profile/events/EventTab.tsx
- src/components/reservant/profile/friends/Friend.tsx
- src/components/reservant/profile/friends/FriendTab.tsx
- src/components/reservant/profile/reservations/Reservation.tsx
- src/components/reservant/profile/reservations/ReservationHistoryTab.tsx
- src/components/reservant/profile/reservations/ReservationList.tsx
> gh issue #223

- src/app/App.tsx
- src/components/customerService/CustomerService.tsx
- src/components/customerService/complaints/ComplaintDetails.tsx
- src/components/customerService/complaints/ComplaintsList.tsx
- src/components/customerService/nav/NavBar.tsx
- src/components/reservant/profile/events/EventList.tsx
- src/components/reservant/restaurantManagement/Warehouse/IngredientTable.tsx
- src/components/reservant/restaurantManagement/deliveries/DeliveriesTable.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
- Lista wszystkich reportów pracownika BOK
- Połączono kolumny z akcjami w jedną kolumnę (DeliveriesTable i IngredientTable)
- Sortowanie eventów po dacie i funkcja filtrowania eventów w danym zakresie dat
> Customer service reports list

- src/components/auth/Login.tsx
- src/components/reservant/profile/Profile.tsx
- src/components/reservant/restaurantManagement/restaurants/RestaurantDetails.tsx
- src/components/reservant/restaurantManagement/restaurants/restaurantsList/RestaurantListSection.tsx
- src/components/reservant/restaurantManagement/restaurants/test.tsx
- src/services/types.ts
- tailwind.config.js
Done:
- edycja wiersza naprawiona
- wyświetlanie detali restauuracji i możliwość edycji po kliknięciu na wiersz
- błąd się powinien wypisywać o zablokowanym koncie przy zalogowaniu (nie ma jak tego testować za bardzo, i nie wiedziałam jakiś dać komunikat w sumie)
- zmieniłam wygląd menu w profilu ale nie wiem czy tal lepiej
> Ms edit restaurant

- src/components/customerService/complaints/ComplaintsList.tsx
- src/components/customerService/complaints/ReportActionDialog.tsx
- src/components/customerService/users/User.tsx
- zmieniony ban form na formika ze zwykłymi inputami na liczby
- dopisanie do DataGrid resolutionDate, resolvedBy, isResolved bo nie było
> Changed ban form, small fix in reports list

- src/components/customerService/users/User.tsx
- src/components/reservant/restaurant/events/EventCreationModal.tsx
- src/components/reservant/restaurant/events/EventDetailsModal.tsx
- src/components/reservant/restaurantManagement/Warehouse/AddIngredientDialog.tsx
- src/components/reservant/restaurantManagement/Warehouse/IngredientTable.tsx
- src/components/reservant/restaurantManagement/deliveries/DeliveriesTable.tsx
- src/services/types.ts
- src/translations/en/global.json
- src/translations/pl/global.json
- W profilu użytkownika dla pracownika BOK uwzględnienie czy uzytkownik jest już zbanowany i wyświetlanie tylko odpowiedniego przycisku
- Usunięcie labeli z warehouse i deliveries management
- Dialog potwierdzający dodanie nowego składnika
- Zmieniony Dialog potwierdzający utworzenie eventu
> BOK User bans and some other things

- src/components/customerService/complaints/ReportActionDialog.tsx
- src/components/customerService/users/User.tsx
- src/components/reservant/navigation/navItems/Notifications/Notification.tsx
- src/components/reservant/restaurant/events/EventCreationModal.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
- zmiana wyglądu niektórych inputów w boku
- zmiana wyglądu i działania formularza tworzenia eventu
- naprawienie jednego typu notyfikacji
> small fixes

- src/components/reservant/navigation/navItems/Tools.tsx
- src/components/reservant/profile/events/Event.tsx
- src/components/reservant/profile/events/EventList.tsx
- src/components/reservant/profile/reports/Report.tsx
- src/components/reservant/profile/reservations/Reservation.tsx
- src/components/reservant/profile/reservations/ReservationHistoryTab.tsx
- src/components/reservant/profile/reservations/ReservationList.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
- tailwind.config.js
giga kox jestem za tego tailwinda imo
> added bug report, changed tailwind config

- src/components/customerService/users/User.tsx
- src/components/reservant/profile/Account.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
- opcja usunięcia czyjegoś konta przez pracownika BOK
- opcja usunięcia własnego konta w profilu użytkownika
> usuwanie konta użytkownika przez użytkownika i przez BOK

- src/components/reservant/restaurantManagement/employees/EmployeeManagement.tsx
dodałem freestyle filtrowanie, nie wiem czy opłaca się robić o tą flage issue na backa... raczej nie..
> SPRAWDZIĆ ISSUE PRZED MERGE - fix: removed deleted employees from the table

- src/components/reservant/profile/Account.tsx
- src/components/reservant/profile/events/Event.tsx
- src/components/reservant/profile/events/EventList.tsx
- src/components/reservant/profile/friends/FriendList.tsx
- src/components/reservant/profile/reports/ReportsList.tsx
- src/components/reservant/restaurantManagement/reservations/HistoryTab.tsx
- src/components/reusableComponents/Filters.tsx
- src/components/reusableComponents/Search.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
> szymon gh issues

- src/components/customerService/restaurants/RestaurantDetails.tsx
- src/components/reservant/restaurant/RestaurantReviewForm.tsx
- src/components/reservant/restaurant/onMapView/FocusedRestaurantReviewsList.tsx
- src/components/reservant/restaurantManagement/register/restaurantRegister/RegisterSuccess.tsx
- src/components/reservant/restaurantManagement/restaurants/restaurantReviews/RestaurantReview.tsx
> Ms dark theme issues

- src/components/auth/Login.tsx
- src/components/auth/UserRegister.tsx
- src/components/reservant/restaurantManagement/menus/Menu.tsx
- src/components/reservant/restaurantManagement/menus/MenuDialog.tsx
- src/components/reservant/restaurantManagement/menus/MenuItem.tsx
- src/components/reservant/restaurantManagement/menus/MenuItemDialog.tsx
- src/components/reservant/restaurantManagement/menus/MenuList.tsx
- src/components/reservant/restaurantManagement/restaurants/restaurantsList/RestaurantListSection.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
close #335 
close #334 
close #329
> Ms tranlations issues

- src/components/reservant/restaurant/Checkout.tsx
> szymon gh issue #322 Naprawienie problemów z portfelem 

- src/components/customerService/complaints/ComplaintDetails.tsx
- src/components/customerService/complaints/ComplaintsList.tsx
- src/components/reservant/restaurant/Cart.tsx
- src/components/reservant/restaurant/Checkout.tsx
- src/components/reservant/restaurantManagement/Reports.tsx
- src/components/reservant/restaurantManagement/employees/EmployeeManagement.tsx
- src/components/reservant/restaurantManagement/employees/EmployeeRestaurantManagement.tsx
- src/components/reservant/restaurantManagement/employees/EmploymentsManagement.tsx
- src/components/reservant/restaurantManagement/tabs/ManagementTabs.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
resolves #342 ,
resolves #345 ,
resolves #346 ,
resolves #348 ,
resolves #349 ,
resolves #357 ,
resolves #358
> Added missing translations

- src/components/reservant/profile/events/EventEditDialog.tsx
- src/components/reservant/restaurantManagement/register/restaurantRegister/RegisterSuccess.tsx
- src/components/reservant/restaurantManagement/restaurants/RestaurantDetails.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
close #387
w #391 nie dam razy zmienić koloru border w dark themie
> Ms 391 387

- src/components/customerService/complaints/ComplaintDetails.tsx
- src/components/customerService/complaints/ReportActionDialog.tsx
- src/components/customerService/users/User.tsx
- src/components/reservant/navigation/navItems/Notifications/Notification.tsx
- src/components/reservant/navigation/navItems/Notifications/NotificationList.tsx
- src/components/reservant/navigation/navItems/Notifications/Notifications.tsx
- src/components/reservant/restaurant/events/EventCreationModal.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
> szymon gh issue rozne

- src/components/reservant/navigation/navItems/Notifications/Notification.tsx
- src/components/reservant/navigation/navItems/Tools.tsx
- src/components/reservant/restaurantManagement/register/restaurantRegister/RestaurantRegister.tsx
- src/components/reservant/restaurantManagement/restaurants/restaurantsList/RestaurantListSection.tsx
- src/components/reusableComponents/FriendSelector.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
uwaga! w momencie tworzenia PR to nie działa, gdyż posty zwracają 403 forbidden. Problem prawdopodobnie sam się rozwiąże gdy zmiany backendu zostaną zshipowane na serwer
> 302 bug sprawdzić czy customer ma jak zostać właścicielem

- src/components/ProtectedLayout.tsx
- src/components/reservant/HomePage.tsx
- src/components/reservant/profile/Account.tsx
- src/components/reservant/profile/reservations/Reservation.tsx
- src/components/reservant/restaurant/Checkout.tsx
- src/components/reservant/restaurant/onMapView/FocusedRestaurantReviewsList.tsx
- src/components/reservant/restaurant/visits/Visit.tsx
- src/components/reservant/restaurant/visits/VisitRoot.tsx
- src/contexts/SnackbarContext.tsx
- src/translations/en/global.json
- src/translations/pl/global.json
> szymon gh issue reservation snackbars
